### ISSUE TITLE
Different behaviour of iOS/Android on the + character encoding

### ISSUE THREAD

**Issue by frederikbosch** [capacitor-community/http#101]
When posting data using `application/x-www-form-urlencoded`, the data is encoded differently between iOS and Android. This is because `URLComponents` in Swift does not encode a `+` character, whereas it does in Android. Please see [this SO-post for more detail](https://stackoverflow.com/questions/43052657/encode-using-urlcomponents-in-swift). This bug is generated from [the following line](https://github.com/capacitor-community/http/blame/master/ios/Plugin/Plugin.swift#L375).

If I would be a iOS dev with a Mac, I would have tried to come up with a PR, but I am not and do not have any test environment.

In PR #73 I also see this bug:
- [CapacitorUrlRequest.swift](https://github.com/capacitor-community/http/blob/capacitor-v3/ios/Plugin/CapacitorUrlRequest.swift#L22)
- Maybe also this one: [HttpRequestHandler.swift](https://github.com/capacitor-community/http/blob/capacitor-v3/ios/Plugin/HttpRequestHandler.swift#L72)

**Comment by ptmkenny** [comment]
There is another issue about this: #62
