### ISSUE TITLE
(Capacitor 3) Plugin.swift -> downloadFile() has no implementation for iOS

### ISSUE THREAD

**Issue by lincolnthree** [capacitor-community/http#104]
**Describe the bug**

In the capacitor 3 branch of this project, when files are downloaded, the request is made, but file is never saved to disk.

See diff here of missing implementation in Plugin.swift:

https://github.com/lincolnthree/capacitor-community-http/commit/c693de967ddff9ccb4a38e6dfa16e94a02de214e

**To Reproduce**
1. Try to download a file. Nothing saved :)

**Expected behavior**
Files should be saved to disk just like on master branch.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Native

**Smartphone (please complete the following information):**
iOS real and simulated devices

**Additional context**

**Comment by leo6104** [comment]
I think https://github.com/capacitor-community/http/blob/capacitor-v3/ios/Plugin/Plugin.swift#L42 should be changed

Now, it just call `request` (not download method) 

Expectation. 
```

    @objc func downloadFile(_ call: CAPPluginCall) {
        // Protect against bad values from JS before calling request
        guard let u = call.getString("url") else { return call.reject("Must provide a URL") }
        guard let _ = call.getString("filePath") else { return call.reject("Must provide a file path to download the file to") }
        guard let _ = URL(string: u) else { return call.reject("Invalid URL") }

        do {
            try HttpRequestHandler.download(call)
        } catch let e {
            call.reject(e.localizedDescription)
        }
    }
```

**Comment by lincolnthree** [comment]
That makes sense! I didn't dig too deep to see where this function had moved. Looks like you found it :)

**Comment by lincolnthree** [comment]
@leo6104 I think that method may not be working as intended. I still don't get files downloaded when calling it. Is it working for you?

**Comment by thomasvidas** [comment]
I just published `1.0.0-alpha.1` on npm. Can you let me know if that fixes your issue? If it does not, can you provide a reproducible example? I'm not able to reproduce your issue

**Comment by lincolnthree** [comment]
The new Alpha.1 seems to be unusable without modification, as it targets iOS 11:

> @capacitor-community/http/ios/Plugin/Plugin.swift:3:8: Compiling for iOS 11.0, but module 'Capacitor' has a minimum deployment target of iOS 12.0: /Library/Developer/Xcode/DerivedData/App-ewnizagrywofygemcnpulcdczdjo/Build/Products/Debug-iphonesimulator/Capacitor/Capacitor.framework/Modules/Capacitor.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

**Comment by lincolnthree** [comment]
Wait, I may have misinstalled. Ugh. Sorry.

**Comment by lincolnthree** [comment]
@thomasvidas Confirmed! The latest alpha.1 fixes the issue (along with a few other warnings about incorrect method configuration.) Thank you!

**Comment by thomasvidas** [comment]
Perfect. Glad it was just me calling the wrong function 😅
