### ISSUE TITLE
HttpWeb.request

### ISSUE THREAD

**Issue by jongbonga** [capacitor-community/http#111]
**Describe the bug**
I'm getting an error after upgrading 

to @next
```
    TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at buildRequestInit (VM3122 web.js:67)
    at Module.request (VM3122 web.js:86)
    at HttpWeb.request (VM3122 web.js:218)
    at VM3083 vendor.js:53124
    at ZoneDelegate.invoke (VM3082 polyfills.js:3018)
    at Object.onInvoke (VM3083 vendor.js:102811)
    at ZoneDelegate.invoke (VM3082 polyfills.js:3017)
    at Zone.run (VM3082 polyfills.js:2780)
    at VM3082 polyfills.js:3922
```

To 0.3.0

```
    TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at HttpPluginWeb.makeFetchOptions (web.js:42)
    at HttpPluginWeb.<anonymous> (web.js:68)
    at Generator.next (<anonymous>)
    at web.js:7
    at new ZoneAwarePromise (zone-evergreen.js:1387)
    at push.RdDx.__awaiter (web.js:3)
    at HttpPluginWeb.request (web.js:67)
    at ApiService.<anonymous> (api.service.ts:71)
    at Generator.next (<anonymous>)
```

**To Reproduce**
1. npm install @capacitor-community/http@next
2. `await Http.request({ method, url, headers  })`

**Expected behavior**
To work like before (lol) 

**Desktop (please complete the following information):**
 - Browser : Chrome

**Additional context**
upgraded from capacitor v2 to v3. replaced `const { Http } = Plugins` with `import { Http } from '@capacitor-community/http';`

Was originally on 0.2.1

**Comment by thomasvidas** [comment]
Hello 👋  I see you're getting Zone.js errors. Are you using Angular by chance? There is [an open issue about async/await](https://github.com/angular/angular/issues/31730) so I wonder if it is related to that.

Could you provide a reproduction? This seems to work fine for me with the test project included in this repo
```
const ret = await Http.request({
  method: 'GET',
  url: 'http://localhost:3455/get',
});
```

**Comment by jongbonga** [comment]
I migrated 2 apps to v3

- 1 has no issue with the upgrade, straight forward
- 2nd one is a bit tricky because of the Digest authentication

```
async request(method, uri, params?) {
    const ha2 = Md5.hashStr(`${method}:${uri}`);
    const nonce = new Date().getTime();
    const response = Md5.hashStr(`${this.auth?.ha1}:${nonce}:${ha2}`);
    const options = params ? new HttpParams({ fromObject: params }).toString() : null;
    const Authorization = `Digest username="${this.auth?.username}",realm="${realm}", nonce="${nonce}",uri="${uri}",response="${response}"`;
    const url = `${base}${uri}`;
    const headers = {
      'X-Concursive-Key': `key=${key}`,
      'content-Type': 'application/x-www-form-urlencoded',
      Authorization
    };

    let request: HttpResponse;

    if (this.platform.is('capacitor')) {
      if (!params) {
        params = {};
      }
      params.format = 'json';

      if (method === 'GET') {
        request = await Http.request({
          method,
          url,
          headers,
          params
        });
      } else {
        request = await Http.request({
          method,
          url,
          headers,
          data: params
        });
      }
    } else {
      request = await Http.request({
        method,
        url: options ? `${url}?format=json&${options}` : `${url}?format=json`,
        headers
      });
    }

    return request.data;
  }
```

the snippet above works fine with 0.2.1, but doesn't with >= 0.3

**Comment by jongbonga** [comment]
There is nothing on the Network tab. the `Http.request({})` throw a preflight error on device, but nothing on browser

**Comment by thomasvidas** [comment]
I just pushed up a potential fix to the v3 branch. 🤞 this is it. Can you try installing via github to see if this fixes your issue? This should be the command.

```
npm i git://github.com/capacitor-community/http.git#capacitor-v3
```

If not I'll take a deeper look at the issue

**Comment by jongbonga** [comment]
`Module not found: Error: Can't resolve '@capacitor-community/http'`

**Comment by thomasvidas** [comment]
Oh duh, because the dist isn't included on GitHub. My mistake. I'll push this to npm in the next alpha

**Comment by jongbonga** [comment]
Hi there

any update on this?

**Comment by thomasvidas** [comment]
Once the next RC is out soon I'll release a new alpha. Don't worry I haven't forgotten 😄

**Comment by thomasvidas** [comment]
@jongbonga I've released 1.0.0-alpha.4. Let me know if this fixes your issue

**Comment by jongbonga** [comment]
> @jongbonga I've released 1.0.0-alpha.4. Let me know if this fixes your issue

Hi, only seeing alpha 4

**Comment by thomasvidas** [comment]
`1.0.0-alpha.4` is the newest version released two days ago. It should include the potential fix for your issue

**Comment by jongbonga** [comment]
Sorry, I meant alpha 2! and I checked on the [releases](https://github.com/capacitor-community/http/releases) but didn't see it.

I will refresh and give you feedback

**Comment by jongbonga** [comment]
hey @thomasvidas , new error alert!! 
`TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.`

**Comment by thomasvidas** [comment]
Sorry for the lack of response, trying to focus on the final release of Capacitor 3.

For the fetch error see [here](https://github.com/whatwg/fetch/issues/551). The fetch spec doesn't allow you to use `GET` or `HEAD` requests with a body.  So if you have anything in `data` when you make one of those requests it will fail since we use `window.fetch` as the http handler on web.

If you have any additional errors related; can you provide a tiny, reproducible github repo and open another issue so I can take a look at it? Don't want to clog up this issue!

**Comment by jongbonga** [comment]
Hi 

Sorry for the late reply.
I literally follow the readme instruction. 


> I migrated 2 apps to v3
> 
> * 1 has no issue with the upgrade, straight forward
> * 2nd one is a bit tricky because of the Digest authentication
> 
> ```
> async request(method, uri, params?) {
>     const ha2 = Md5.hashStr(`${method}:${uri}`);
>     const nonce = new Date().getTime();
>     const response = Md5.hashStr(`${this.auth?.ha1}:${nonce}:${ha2}`);
>     const options = params ? new HttpParams({ fromObject: params }).toString() : null;
>     const Authorization = `Digest username="${this.auth?.username}",realm="${realm}", nonce="${nonce}",uri="${uri}",response="${response}"`;
>     const url = `${base}${uri}`;
>     const headers = {
>       'X-Concursive-Key': `key=${key}`,
>       'content-Type': 'application/x-www-form-urlencoded',
>       Authorization
>     };
> 
>     let request: HttpResponse;
> 
>     if (this.platform.is('capacitor')) {
>       if (!params) {
>         params = {};
>       }
>       params.format = 'json';
> 
>       if (method === 'GET') {
>         request = await Http.request({
>           method,
>           url,
>           headers,
>           params
>         });
>       } else {
>         request = await Http.request({
>           method,
>           url,
>           headers,
>           data: params
>         });
>       }
>     } else {
>       request = await Http.request({
>         method,
>         url: options ? `${url}?format=json&${options}` : `${url}?format=json`,
>         headers
>       });
>     }
> 
>     return request.data;
>   }
> ```
> 
> the snippet above works fine with 0.2.1, but doesn't with >= 0.3

**Comment by jongbonga** [comment]
I guess I found what was breaking my calls on web: `'content-Type': 'application/x-www-form-urlencoded'`.
