### ISSUE TITLE
Add application name to user agent.

### ISSUE THREAD

**Issue by bdiesel** [capacitor-community/http#113]
**Is your feature request related to a problem? Please describe.**
I cannot figure out how to override the default user-agent for iOS. 

**Describe the solution you'd like**
I would like to extend the current user agent something as something along the format of <AppName>/<AppVersion> CFNetwork/<CFNetworkVersion> Darwin/<DarwinVersion>

**Describe alternatives you've considered**
In android I can set a system property to append my application name to the user-agent string.  In iOS it looks like UrlSession.shared  is not configurable.  I tired overriding user-agent as header and that wasn't effective.  I then tried changing the UrlSession from shared to default which allowed me to pass is a then set the user-agent using a httpAdditionalHeaders on URLSessionConfiguration

**Additional context**
If I were to create a pr to add method to configure the User-Agent would you consider adding it to the projecT?

**Comment by bdiesel** [comment]
This is actually exactly how this works.   My App was not named properly.

**Comment by Jack-G-Smith** [comment]
@bdiesel I know this was super long ago but do you remember where you set the  App Name for this plugin? currently my user agent is just coming in with `App/6.x.x CFNetwork/x.x.x Darwin/x.x.x`

if you remember where you set that, I would be forever in your debt because I cannot find it for the life of me...

**Comment by bdiesel** [comment]
It was just a matter of correctly configuring the build settings for the app.  I believe the field was Product Name which needed to be set correctly.  This link may help.  https://developer.apple.com/forums/thread/675823
