### ISSUE TITLE
Cancel Http request

### ISSUE THREAD

**Issue by pentabarf** [capacitor-community/http#116]
I have an android foreground service which periodically syncs data with my backend. In Android Doze Mode the request will get blocked and fire all at once when wakeup from doze which sometimes crashes my app.

For this a cancel function to stop the requests after a timeout (in combination with https://www.npmjs.com/package/p-timeout) would be nice.

Alternatively I can use the Angular HttpClientModule wich is based on Observables. So i just unsubscribe using the timeout pipe.
The disadvantage is missing SSL Pinning, Native Threading etc.

@capacitor-community/http based on Observables also would be nice ;)

**Comment by pentabarf** [comment]
Ooups i was overlooking,

you already have timeout options. I will try this out.

  readTimeout?: number;
  connectTimeout?: number;

**Comment by thomasvidas** [comment]
No worries. I'll go ahead and close this since the timeouts should work for your use case
