### ISSUE TITLE
Uniform response headers structure

### ISSUE THREAD

**Issue by spaghettiguru** [capacitor-community/http#119]
First of all, thanks a lot for the plugin to everyone that is/was working on it. We use it to solve issue with session cookie on IOS and it helps.

**Is your feature request related to a problem? Please describe.**
A `headers` property of the object returned by the `await Http.request(...)` call contains different data structure on each platform. It is array on Android and an object on IOS.

**Describe the solution you'd like**
It would be nice to have the headers property return the same data structure irrespective of the platform.

Currently I solve this issue by using condition in the code, but I think it would be better to have headers property value in the same format on both platforms.

What do you think?

**Comment by thomasvidas** [comment]
Hello 👋 

The latest code on the `capacitor-v3` branch has the headers property returning both as Objects, so I'll go ahead and close this

<img width="791" alt="Screen Shot 2021-05-18 at 2 03 09 PM" src="https://user-images.githubusercontent.com/8182078/118701586-e1474100-b7e1-11eb-8e09-11c622b2f790.png">
