### ISSUE TITLE
Data object not getting assigned for anything not json

### ISSUE THREAD

**Issue by andysousa** [capacitor-community/http#12]
**Describe the bug**
I was trying to get the plugin to work with an OAuth call and quickly realized the data block wasn't being set correctly.  

For example

```
   const ret = Http.request({
      method: 'POST',
      url: '/api/auth/connect/token',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      data: urlSearchParams.toString()
    });
```

When i took a look at the web implementation of the plugin, makeFetchOptions(...) doesn't set the body of the request for any content type that isn't json

```
    makeFetchOptions(options, fetchExtra) {
        const req = Object.assign({ method: options.method || 'GET', headers: options.headers }, (fetchExtra || {}));
        const contentType = this.getRequestHeader(options.headers || {}, 'content-type') || '';
        if (contentType.indexOf('application/json') === 0) {
            req['body'] = JSON.stringify(options.data);
        }
        else if (contentType.indexOf('application/x-www-form-urlencoded') === 0) {
        }
        else if (contentType.indexOf('multipart/form-data') === 0) {
        }
        return req;
    }
```

**Expected behavior**
I would expect the data to be set for other types as well.  This won't work with auth calls as a result.  I have found this doesn't work in the native implementations either.

**Comment by pixelbucket-dev** [comment]
Same problem here. We're trying to do a auth0 request via iOS implementation. The response returns with

```
data: Object
    error: "invalid_request"
    error_description: "grant_type is required"
```

**Comment by pixelbucket-dev** [comment]
Our request looks like this

```ts
return Http.request({
    method: 'POST',
    url: 'SOME_ENDPOINT',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded'
    },
    data: {
        username,
        password,
        grant_type: 'password',
        client_id: 'SOME_CLIENT_ID',
        client_secret: 'SOME_CLIENT_SECRET'
    }
});
```

**Comment by andysousa** [comment]
I had started putting together the fix for this to submit a PR and got pulled into a few different directions.  I will see if i can get to it and share with you to test out.  Not sure if @mlynch is still doing active dev on this.... but would be a quick fix.

**Comment by mlynch** [comment]
PR welcome if you have something soon, if not I can take a look in a few days

**Comment by andysousa** [comment]
I have the web and android one working, but my swift is just not that strong.  Maybe you could tell me where to look @mlynch?

This is where the data should be getting set in the mutate function, but that is always nil
```

func mutate(_ call: CAPPluginCall, _ url: URL, _ method: String, _ headers: [String:String]) {
    let data = call.getObject("data")
    
```

**Comment by mlynch** [comment]
@andysousa can you open a PR with the android/web changes and then I can help figure out where the Swift side should happen?

**Comment by andysousa** [comment]
@mlynch i was mistaken, android wasn't working for me either.  The CAPPluginCall just doesn't have an object called "data" in it for ios/Android.  Guessing thats happening at the Cap runtime level... but haven't dug in yet.

**Comment by andysousa** [comment]
oh, i see the issue... data is being set with getObject... but for OAuth calls, it needs to be getString().  Not sure the downstream ramifications of this... let me see if i can put something together.

**Comment by andysousa** [comment]
so using a data object for OAuth works in ios/android... the code is smart enough to check the content type and put it as part of the object correctly.  This doesn't work the same in the web implemention, so i will submit a PR so that the web matches the logic in ios/Android.

In the meantime @pixelbucket-dev to for it to work in Native, all you need to do is put the data in an object block.  The code you pasted won't work because in OAuth, the body should be one string.  So you would want to do this.

```
   const ret = Http.request({
      method: 'POST',
      url: '/api/auth/connect/token',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      data: {
        body: "username=username&password=password&grant_type=password&client_id=something&clientsecret=something"      
      }
    });
```

**Comment by andysousa** [comment]
added PR https://github.com/capacitor-community/http/pull/17

**Comment by andysousa** [comment]
@pixelbucket-dev I was wrong, as i dig deeper into the ios implementation... the way you have it should work, its is doing a queryItems?.append so it will build the string appropriately.  I think the only issue with your code snippet is your need to have the username and password keys.

I also don't like my implementation in the PR based on this.  So i am going to go back and clean it up.

**Comment by andysousa** [comment]
ok, PR updated... give that a spin

**Comment by pixelbucket-dev** [comment]
@andysousa I had a look at the TS code, looks good. 

I remember when I tested our request with this plugin I saw the query params being correctly stringified. Might try again with your `body` workaround. Thank you.
