### ISSUE TITLE
Do we have server trust mode check and uncheck

### ISSUE THREAD

**Issue by achakra21** [capacitor-community/http#123]
1. Like Cordova plug-in advance http , here do we have any such method to connect untrusted server ? I mean server with expired ssl ?

2. Can we use it on web browser , does it resolves the core issue like we have it works with advance http from Skillman .

3. Does it sends preflight request before connecting to server ?

**Comment by thomasvidas** [comment]
1. No, it does not handle it by default. You would need to modify the native Android and iOS projects to allow for insecure connections. But once you set those properties this library will work fine.
2. Yes, you can use this in a web browser
3. On iOS and Android there are no CORS requests needed, so no
