### ISSUE TITLE
Headers and params not set on web implementation

### ISSUE THREAD

**Issue by danielsogl** [capacitor-community/http#13]
**Describe the bug**

The http headers are not send when set on web implementation

**To Reproduce**

This is just one example from one of my applications 

```ts
    const result = await (Http as HttpPlugin).request({
      method: 'GET',
      url,
      // handle cors issues
      headers: {
        origin: 'x-requested-with',
      },
      params: {
        package: encodeURI(decodeURI(packageName)).replace('%252F', '%2F'),
        until: format(new Date(), 'YYYY-MM-DD'),
        from: fromDate,
      },
    });
```

**Expected behavior**

The we implementation of the plugin should set http headers and url params.

**Comment by mlynch** [comment]
Thanks will take a look in the next day or so

**Comment by mlynch** [comment]
I'm confused, just tested it and it's working fine for me. However, I noticed if I used the `origin` header, that got overwritten somewhere in the pipeline and likely out of our control. Have you tried with other headers?

**Comment by jongbonga** [comment]
I'm experiencing the same issue with `params` & `data` on web.
with :
```
const headers = {
      'content-Type': 'application/x-www-form-urlencoded',
      Authorization
    }
```

**Comment by DarrenAllen** [comment]
@mlynch The issue @jongbonga  mentioned above appears to be the same issue fixed here: https://github.com/capacitor-community/http/pull/17  Is there any chance we'll get this released soon? I'm trying to get this plugin to work with OAuth and this is the issue. Thank you!

**Comment by kaimallie** [comment]
Looks like for now it's only working with the header: `'Content-Type': 'application/json'`

**Comment by dmastag** [comment]
Yes @kaimallie 
Its because the fix has not been released to npm yet

**Comment by thomasvidas** [comment]
Closing this since the fix has already been merged to `master`. I'm preparing a 0.3.0 release for later this week on npm but if you need the fix now you can clone the repo and build the project with the following command. It builds a `/dist` folder

```bash
npm install
npm run build
```
