### ISSUE TITLE
Compatibility for CJS

### ISSUE THREAD

**Issue by ultimate-tester** [capacitor-community/http#131]
**Is your feature request related to a problem? Please describe.**
I am using Browserify to pack my app, there's currently no support for CJS modules (using require instead of import)

**Describe the solution you'd like**
When generating the files for capacitor, other modules are using rollup to also generate the CJS related files. The package.json needs a small modification to have the proper entry point.

**Additional context**
I can make a pull request for this! It should just be a minute's work :)

**Comment by ultimate-tester** [comment]
I've already submitted the PR, had some free time. #132

**Comment by thomasvidas** [comment]
Merged in via #132, will be released in 1.1.0 soon
