### ISSUE TITLE
Download file behind protected api

### ISSUE THREAD

**Issue by visiblesoft-org** [capacitor-community/http#135]
**Describe the bug**
An error is received when trying to download a file from a protected route. Only the word Error is displayed in browser inspect.
All other requests like GET, PUT, POST are working fine.
I've added a message received in Android Studio console with an error from Http plugin.

**To Reproduce**
This is the code:

```
  public async getPhoto(orderId: number, photoName: string) {
    const options: HttpDownloadFileOptions = {
      url: environment.apiUrl + `/api/tablet/photos/${orderId}/${photoName}`,
      filePath: photoName,
      fileDirectory: Directory.Cache,
      headers: {
        'Content-Type': 'image/jpg'
      }
    };

    const response: HttpDownloadFileResult = await Http.downloadFile(options);
    return response.path;
}
```

**Expected behavior**
Download the file, or display a detailed error.

**Screenshots**
![image](https://user-images.githubusercontent.com/78475380/122384911-7322a500-cf6c-11eb-8f52-ee873998711b.png)

In Android Studio:

E/Capacitor/Plugin: Error
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toUpperCase()' on a null object reference
        at com.getcapacitor.plugin.http.HttpRequestHandler.downloadFile(HttpRequestHandler.java:337)
        at com.getcapacitor.plugin.http.Http.downloadFile(Http.java:139)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:584)
        at com.getcapacitor.-$$Lambda$Bridge$25SFHybyAQk7zS27hTVXh2p8tmw.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
D/Capacitor: Sending plugin error: {"save":false,"callbackId":"40118207","pluginId":"Http","methodName":"downloadFile","success":false,"error":{"message":"Error"}}

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: N/A
 - Version: N/A

**Smartphone (please complete the following information):**
 - Device: Android emulator Pixel XL API 30
 - OS: Android 11
 - Browser: stock browser
 - Version

**Comment by visiblesoft-org** [comment]
Following change defined in https://github.com/capacitor-community/http/pull/133/commits/ebb2744e58b8b7fbe842a55f7ee2db802539461f now the app is working.

It's needed to make another change also in line 389 of the same file "HttpRequestHandler.java" and add "POST" if you are working with uploadFile method:

`String method = call.getString("method", "POST").toUpperCase();`

Please, fix the plugin.
Regards
Jose

**Comment by hussainarthuna** [comment]
Same error I am receiving when using uploadFile method on Android.

**Comment by thomasvidas** [comment]
You can specify `method: POST` in the download options. The default option is `GET`. This is on the `1.1.0` branch and will be released on npm soon.

**Comment by najmulansari** [comment]
> You can specify `method: POST` in the download options. The default option is `GET`. This is on the `1.1.0` branch and will be released on npm soon.

Is this fix released on npm? After I upgraded to Capacitor 3, I started getting error while downloading file.

**Comment by visiblesoft-org** [comment]
> > You can specify `method: POST` in the download options. The default option is `GET`. This is on the `1.1.0` branch and will be released on npm soon.
> 
> Is this fix released on npm? After I upgraded to Capacitor 3, I started getting error while downloading file.

Yes, it's working fine... only add "method: POST|GET" to HttpUploadFileOptions. Ej.:

```
const options: HttpUploadFileOptions = {
      url: environment.apiUrl + `/api/tablet/orders/${orderId}/photos`,
      filePath: fileName,
      fileDirectory: Directory.Data,
      method: 'POST',
      name: 'upload'
};
```

**Comment by visiblesoft-org** [comment]
> > You can specify `method: POST` in the download options. The default option is `GET`. This is on the `1.1.0` branch and will be released on npm soon.
> 
> Is this fix released on npm? After I upgraded to Capacitor 3, I started getting error while downloading file.

Yes, it's working fine... only add "method: POST|GET" to HttpUploadFileOptions. Ej.:

```
const options: HttpUploadFileOptions = {
      url: environment.apiUrl + `/api/tablet/orders/${orderId}/photos`,
      filePath: fileName,
      fileDirectory: Directory.Data,
      method: 'POST',
      name: 'upload'
};
```
