### ISSUE TITLE
Error: "Invalid HTTP method/URL pair." when trying to request an image from firebase storage inside folder

### ISSUE THREAD

**Issue by MVDeveloper1** [capacitor-community/http#137]
**Describe the bug**
When I try to request an image from firebase storage if the image is inside a folder, eg ` images/image_name.png`, an `Invalid HTTP method/URL pair` error is shown. But if the image is not inside a folder, the request works fine. I think the error is because some encode that is done and maybe because of the **%2F** that is present in the url when the image is inside a folder.

This error did not happen when I tried the http cordova plugin. Also in the browser this error doesn't happen, only on the device (android, maybe ios too).

This type of url does not work on device. (I removed **https://** here to not create a link)
"firebasestorage.googleapis.com/v0/b/[BUCKET]/o/SOME_FOLDER%2F[image_name.jpg]?alt=media&token=[token]"

This type of url without folder and the **%2F** works fine.
"firebasestorage.googleapis.com/v0/b/[BUCKET]/o/[image_name.jpg]?alt=media&token=[token]"

**To Reproduce**
Just upload an image to firebase storage, add the request for that image url and test on device.

**Expected behavior**
The request should succeed when url contains %2F.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Leeco x626
 - OS: Android 6
 - 
**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome 91

**Additional context**

**Comment by MVDeveloper1** [comment]
The documentation says to use the `shouldEncodeUrlParams` option if we need to keep the URL unencoded in certain cases (already encoded, azure/firebase testing, etc.). The default is true.

But setting this option to false has no effect, the url is still encoded again.

**Comment by MVDeveloper1** [comment]
When `setUrlParams()` function is called the `shouldEncode` parameter is always set to `true`.

https://github.com/capacitor-community/http/blob/6658388aa1689a3bd741f5357154cb8a7f4fb4b8/android/src/main/java/com/getcapacitor/plugin/http/HttpRequestHandler.java#L309

https://github.com/capacitor-community/http/blob/6658388aa1689a3bd741f5357154cb8a7f4fb4b8/android/src/main/java/com/getcapacitor/plugin/http/HttpRequestHandler.java#L87

https://github.com/capacitor-community/http/blob/6658388aa1689a3bd741f5357154cb8a7f4fb4b8/android/src/main/java/com/getcapacitor/plugin/http/HttpRequestHandler.java#L127-L133

And this makes the `%2F` which is [required by firebase](https://firebase.google.com/support/guides/cloud-audit-logging/firebase-management#log_name) to be `/` what then triggers the error.

**Comment by dodomui** [comment]
I'm having the same issue on android, any solution yet?

**Comment by jabi11** [comment]
same here

**Comment by jabi11** [comment]
@MVDeveloper1 Where can I find this line of code in my project?
![image](https://user-images.githubusercontent.com/30546236/131674872-0d232eaa-66ee-486e-8d2b-1d1d53b1ca91.png)

**Comment by jabi11** [comment]
Any solution?
