### ISSUE TITLE
bugfix android receiving plain boolean values

### ISSUE THREAD

**Issue by Frank608** [capacitor-community/http#144]
**Describe the bug**
An Error (JSON Exception) is thrown when receiving plain boolean values from endpoints on android

**To Reproduce**
1. receive plain boolean value from REST-Endpoint

**Expected behavior**
Boolean should be converted to JSON object

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A50
 - OS: Android 11

**Additional context**
https://github.com/capacitor-community/http/pull/90

**Comment by thomasvidas** [comment]
Fixed in #145
