### ISSUE TITLE
'the operation could not be completed' on IOS

### ISSUE THREAD

**Issue by mrteey** [capacitor-community/http#148]
**The Problem**
All requests to my API go through on the web and on android, however, on IOS I keep getting 'the operation couldnt be completed' I have searched everywhere without success thats why I decided to post here, perhaps I can get help.

**To Reproduce**
<img width="1280" alt="Screen Shot 2021-07-17 at 7 39 20 PM" src="https://user-images.githubusercontent.com/34660309/126046657-fc87f6a9-422f-4941-a9ca-ac49f609b128.png">
<img width="1280" alt="Screen Shot 2021-07-17 at 7 39 42 PM" src="https://user-images.githubusercontent.com/34660309/126046663-0c969a07-5fdc-4bf5-876e-50b8011d9883.png">

**Expected behavior**
With a successful request, I should get a HttpResponse Promise

**Screenshots**
![Screen Shot 2021-07-17 at 2 56 09 PM](https://user-images.githubusercontent.com/34660309/126046674-843eb1d5-0547-46c9-9e68-b80969ba8044.png)

**Smartphone:**
 - Device: iPhone6
 - OS: iOS12

**Comment by rathoreabhijeet** [comment]
Facing same issue in iOS 14.5, iPhone 12 with Capacitor 3. The plugin works fine on android though. 

It seems the `NSURLErrorDomain -1020` is a `kCFURLErrorDataNotAllowed` error, not sure why that should come here as it looks like a data network related error. 

For now, I'm patching iOS http calls with [Cordova Http Plugin](https://github.com/silkimen/cordova-plugin-advanced-http). Really looking forward for a fix.

**Comment by ldikmans** [comment]
we face the same issue with delete, see [issue 153](https://github.com/capacitor-community/http/issues/153), but not with post or put or get

**Comment by mrteey** [comment]
> Was facing same issue in iOS 14.5, iPhone 12 with Capacitor 3.
> 
> Calling API with `Http.request({ ...options, method: 'GET' })` works for me on iOS 👍

I will give this a try and report

**Comment by joeflateau** [comment]
fixed by my PR #152 waiting to be merged

**Comment by thomasvidas** [comment]
Fixed in #152
