### ISSUE TITLE
Error: "Http" plugin is not implemented on ios

### ISSUE THREAD

**Issue by louis123562** [capacitor-community/http#150]
hey,

i get the following error when trying a post: 
`Error: "Http" plugin is not implemented on ios`

```
    //return promise
    return Http.request({
      url: "www.example.org",
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      data: [
        action => "do_smth"
      ]
    })
```

<img width="672" alt="grafik" src="https://user-images.githubusercontent.com/36068395/126509814-0e9a72dc-d0c7-4955-8367-1a1b4aebf7a0.png">

What am I doing wrong??

**Comment by rathoreabhijeet** [comment]
Doesn't look like Http request issue, looks like the plugin is not being read at all. Faced similar issue in Google auth plugin, but removing and re-adding the platform and/or redoing `Pod install` might help.

Also if you're on M1 chip mac, you'd want to run xCode using Rosetta to build the app properly. 

I can confirm this Http plugin works for me on iOS 14.5.

**Comment by rene-mueller** [comment]
@louis123562 you need to `cap sync` your source with the native project

**Comment by louis123562** [comment]
Thanks @rathoreabhijeet @rene-mueller, i will try that later today :)
On iOS my app is also white after startup... idk if this is correlated to this issue.

**Comment by thomasvidas** [comment]
Yeah, this is unrelated to the HTTP plugin code. A `npx cap sync` or `pod install` should fix this issue
