### ISSUE TITLE
What is this, my app was rejected from app store, because http plugin uses UIWebView?

### ISSUE THREAD

**Issue by bazuka5801** [capacitor-community/http#151]
https://github.com/capacitor-community/http/blob/e257bd1adbee3597ad969c088dfb0c859c07ea42/ios/Pods/Target%20Support%20Files/CapacitorCordova/CapacitorCordova-umbrella.h#L24

**Comment by bazuka5801** [comment]
We need remove this

**Comment by thomasvidas** [comment]
This was due to the `Pods` folder being included in the project files. I've released 1.1.2 which fixes this issue
