### ISSUE TITLE
DELETE calls should not require a body

### ISSUE THREAD

**Issue by 6foot3foot** [capacitor-community/http#164]
**Describe the bug**
Calling a delete rest endpoint with out causes an error and prevents call from being made.

**To Reproduce**
1. Call a delete rest endpoint with no body.
2. e.g. [DELETE] https://mygreatapi/resource/1234

**Expected behavior**
Delete calls in general usually don't have bodies, it's not forbidden but most apis don't use it and some go so far as to forbid it.  In Either case including a body on a delete to a resource is usually not applicable in a fully restful api.

**Desktop (please complete the following information):**
 - iOS

**Additional context**
The issue is in the HttpRequestHandler.swift file where 'isHttpMutate' set for multiple calls, and if that's set it explicitly checks for a body in the request, if it doesn't find one it rejects the call.  Mutate with body make sense for 'PUT', 'POST', 'PATCH', but 'DELETE' should not be included in that logic as majority of calls will not have a body. 

**Supporting information**
https://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request

**Proposed fix tested in fork**
`
// Change this
let isHttpMutate = method == "DELETE" ||
    method == "PATCH" ||
    method == "POST" ||
    method == "PUT";

// To This
let isHttpMutate =
    method == "PATCH" ||
    method == "POST" ||
    method == "PUT";
`

**Comment by thomasvidas** [comment]
Closing since this is merged in #196
