### ISSUE TITLE
getCookies url option is ignored/not implemented?

### ISSUE THREAD

**Issue by ptmkenny** [capacitor-community/http#169]
**Describe the bug**

The README suggests using `getCookies()` like this:

```
const getCookies = async () => {
  const cookies: HttpCookie[] = await Http.getCookies({
    url: 'http://example.com',
  });
};
```

So I tried calling `getCookies()` in my Ionic PWA and did not get the results I expected (no matter what I put in `url`, I only got cookies for `localhost`, which I am using to test my app.

For example:

```
  const cookies: any = await Http.getCookies({
    url: 'microsoft.com',
  });
  console.log('http cookies', cookies);
```

When I check this code in my PWA, it returns two google analytics cookies (for `localhost`).  I expected that I would get nothing, since I set `microsoft.com` as the URL.

http 1.2.0

I checked the code [here](https://github.com/capacitor-community/http/blob/master/src/cookie.ts) and I couldn't find anything about a URL.  So perhaps the URL option is not implemented?  What is the `url` option supposed to do in the context of `getCookies()`?

**Comment by thomasvidas** [comment]
The `url` parameter is only used on the native application side. On the web, it is ignored.

Android: [Link](https://github.com/capacitor-community/http/blob/400961d37adbe5cfd0214d0e3355b0fdf47afa60/android/src/main/java/com/getcapacitor/plugin/http/Http.java#L42)
iOS: [Link](https://github.com/capacitor-community/http/blob/400961d37adbe5cfd0214d0e3355b0fdf47afa60/ios/Plugin/Plugin.swift#L8)

For native applications, you need to specify the server URL of the cookie to use the native cookie store while on web you don't need it. Hence why it's ignored on web.
