### ISSUE TITLE
`decodeURIComponent` when getting cookies and `encodeURIComponent` when setting them

### ISSUE THREAD

**Issue by IlCallo** [capacitor-community/http#18]
**Describe the bug**
All web frameworks encode Cookies with a function similar to `encodeURIComponent` (eg. Laravel XSRF-TOKEN) and consequentially need to be decoded with `decodeURIComponent` when retrived by `Http.getCookies` (and encoded when set).

**Expected behavior**
Cookies should be encoded with `encodeURIComponent` when set and decoded with `decodeURIComponent` when retrieved.

**Additional context**
https://stackoverflow.com/questions/1969232/what-are-allowed-characters-in-cookies/1969339#1969339

https://stackoverflow.com/questions/49205195/should-cookie-values-be-url-encoded

**Comment by thomasvidas** [comment]
Merged into `capacitor-v3` branch, so I'm closing this issue
