### ISSUE TITLE
Ignore request to self-signed certificate 

### ISSUE THREAD

**Issue by kaleming** [capacitor-community/http#181]
Hello,

I am using `capacitor-community/http` with ionic 5 and vuejs in order to make api requests.
Everything worked fine so far, however I could not found a way to make requests to internal ip addresses like `https:192.x.x.x` that contains a self-signed certificate. 

I get the following error:

`SSLHandshakeException`

**Screenshots**
On Postman I can solve this using :

![image](https://user-images.githubusercontent.com/51836477/137721341-a568393c-69e1-4c9c-ae7a-2f056f9f329b.png)

**Expected behavior**
I would like to know if it possible to disable ssl verification `capacitor-community/http`, or if you guys suggests a workaround to this situation in particular.

**Comment by 0xRenshaw** [comment]
> IMHO there is a gap in plugin documentation. You should:
> 
>     1. Generating self signed CA certificate and add this to device
> 
>     2. Generating certificate for your API service (signed by CA from step 1) for domain name ex. `mypc.local`
> 
>     3. Enable trust to user loaded certificates in appliaction See https://developer.android.com/training/articles/security-config.
> 
> 
> ` res/xml/network_security_config.xml`:
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <network-security-config>
>   <domain-config>
>     <domain includeSubdomains="true">local</domain>
>       <trust-anchors>
>         <certificates src="user" />
>      </trust-anchors>
>   </domain-config>
> </network-security-config>
> ```

Hi @sla100
Do you have to do something similar for iOS ? I was hoping id be able to replace cordova-advanced-http with this http package however I cannot get self-signed certs to work on iOS without enabling root trust where as in the cordova one I dont have to nor do any other config to use a self-sign-cert

**Comment by sla100** [comment]
> Do you have to do something similar for iOS

Unfortunately, I do not know this system and I do not have such a device for testing either.

**Comment by thomasvidas** [comment]
Added docs in #190
