### ISSUE TITLE
Allow CSRF tokens to be added to the header when uploading a file

### ISSUE THREAD

**Issue by ptmkenny** [capacitor-community/http#182]
**Is your feature request related to a problem? Please describe.**

I am using this plugin with a Drupal 9 backend.

To make requests over HTTP, Drupal requires a CSRF token for cross-site forgery protection.

When POSTing or PATCHing, it is easy to add the token:

```
    const csrfToken = await getCsrfToken();
    if (typeof csrfToken === 'string' && options.headers) {
      options.headers['X-CSRF-Token'] = csrfToken;
```

However, when uploading a file, there is no way to override the headers:

`TS2339: Property 'headers' does not exist on type '{ method: string; url: string; name: string; filePath: string; }'.`

**Describe the solution you'd like**

Add a way to append a token when uploading a file, since some backends require it.

**Describe alternatives you've considered**

I can do this with axios and JWTs, but that defeats the point of using this plugin.

I also tried using `POST` to upload the file using the same parameters that I do with Axios:

```
const fetchPostFileOptions = (url: string, data: unknown): HttpOptions => ({
  method: 'POST',
  url,
  data,
  headers: {
    Accept: 'application/vnd.api+json',
    'Content-Disposition': 'file; filename="myfile.jpg"',
    'Content-Type': 'application/octet-stream',
  },
  webFetchExtra: {
    credentials: 'include',
  },
});
```

However, in this case, Drupal gives me `The website encountered an unexpected error. Please try again later.`  I don't have further debugging information about that, but very similar code works in axios with a JWT.

**Comment by thomasvidas** [comment]
I'm going to close this issue since you opened another, similar issue with #191.

**Comment by ptmkenny** [comment]
After debugging this further this morning, I see that [headers](https://capacitor-community.github.io/http/docs/interfaces/definitions.httpuploadfileoptions.html) is in fact supported, and the problem was that I was initializing my object in a brittle way.
