### ISSUE TITLE
Data is required when using delete, although documentation states it is optional

### ISSUE THREAD

**Issue by ldikmans** [capacitor-community/http#184]
We upgraded from 1.0.0 to 1.3.0 and our delete calls stopped working. 

We had this issue before (https://github.com/capacitor-community/http/issues/153 ). The problem occurs on line 163 of https://github.com/capacitor-community/http/blob/master/ios/Plugin/HttpRequestHandler.swift 

```
let isHttpMutate = method == "DELETE" ||
            method == "PATCH" ||
            method == "POST" ||
            method == `"PUT";
```

and then on line 181 this is used te determine if we should get data to set the request body

` ```
if isHttpMutate {
            do {
                guard let data = call.jsObjectRepresentation["data"]
                else {
                    throw CapacitorUrlRequest.CapacitorUrlRequestError.serializationError("Invalid [ data ] argument")
                }
                
                try request.setRequestBody(data)
            } catch {
                // Explicitly reject if the http request body was not set successfully,
                // so as to not send a known malformed request, and to provide the developer with additional context.
                call.reject("Error", "REQUEST", error, [:])
                return;
            }
        }
```

in my opinion it should be allowed to send an empty body with delete (and arguably even with post or put or patch, if you want to create something based on the URL parameters). 

Steps to reproduce the behavior:

Create a call with the plugin 1.0.0 that uses delete with no body

```
import { HttpHeaders, Http } from '@capacitor-community/http';

const httpHeaders = { 'content-type': 'application/json' };
const result = await Http.del({
url: url,
headers: httpHeaders
});
}
```

Run it  in 1.1.0 -> success
Upgrade to 1.3.0

Run it 
Error occurs "REQUEST"
All other calls are still working (post, get, put)

Expected behavior
successful call

now when I add an empty data object, it works:
```
import { HttpHeaders, Http } from '@capacitor-community/http';

const httpHeaders = { 'content-type': 'application/json' };
const result = await Http.del({
url: url,
data: {},
headers: httpHeaders
});
}
```

**Comment by ptmkenny** [comment]
This is the same issue as https://github.com/capacitor-community/http/issues/164.

**Comment by ldikmans** [comment]
you are right, I will close this one
