### ISSUE TITLE
Capacitor transition

### ISSUE THREAD

**Issue by silkimen** [capacitor-community/http#20]
Hi @mlynch ✌️, I've heard about this plugin today in Ioniconf keynote (great job by the way) and wanted to reach out to you. Don't know if I chose the right place 😅. I'm the maintainer of [cordova-plugin-advanced-http](https://github.com/silkimen/cordova-plugin-advanced-http). I like the idea of capacitor and I do truly believe that it'll be the future of hybrid app development. But for the time being a lot of people are still using cordova (me too). HTTP requests are one of the essential functionalities needed for this purpose.

Maybe we can work together to make the transition easier? Bringing the feature list in sync with this plugin maybe? What do you think?

**Comment by aparajita** [comment]
@silkimen It would be super awesome if you could get that plugin to run on capacitor. Sorry @mlynch, but this plugin is barely ready for prime time. We really need something more robust!

**Comment by mlynch** [comment]
Hey all, PR's are more than welcome! Happy to have more contributions to make the plugin more robust. Will be happy to review anything

**Comment by aparajita** [comment]
@mlynch Of course PR's are welcome, but my point is there is already an http plugin that is vastly superior to this one that needs to be ported from the ionic-native framework to capacitor. It would be a great service to the Ionic community if, as part of your renewed focus on capacitor, Ionic could create a standard migration path that cordova plugin authors could follow. It would be a real waste not to use all of the cordova code out there.

**Comment by mlynch** [comment]
We did implement backwards compatible support for much of the Cordova plugin API pretty much from the beginning. Many of these plugins do work out of the box. I'm not sure if that one does, however.

**Comment by aparajita** [comment]
Fortunately it does work out of the box. The big question is whether Cordova support will remain in Capacitor in the long term.

**Comment by mlynch** [comment]
I can assure you Cordova support in Capacitor is here to stay!
