### ISSUE TITLE
Granular network debug

### ISSUE THREAD

**Issue by CodeWithOz** [capacitor-community/http#201]
**Is your feature request related to a problem? Please describe.**
Is there a way to get the sort of granular information provided by chrome's netlog tool using this plugin?

**Describe the solution you'd like**
I've tried using netlogs but it seems to only work using actual browser tabs on my computer.

**Describe alternatives you've considered**
Not sure how else to achieve this.

**Additional context**
I've come across [this thread](https://forum.ionicframework.com/t/ionic-native-http-debug/126046/2) but would this only be possible using the external tools mentioned there like Charles Proxy?

**Comment by thomasvidas** [comment]
Not currently no, and it seems a little outside the scope of this project. Maybe I'll make a project one day like `@capacitor-community/http-debug` that hooks into this plugin. But for now, your best bet for debugging network requests is to use one of these. Any of these would work.

- [Android Network Inspector](https://developer.android.com/studio/profile/network-profiler) (Included in Android Studio) - Free
- [Charles Proxy](https://www.charlesproxy.com/) - Free
- [Proxyman](https://proxyman.io/pricing) - Paid
- [Fiddler](https://www.telerik.com/fiddler) - Paid

You could also use something like [Wireshark](https://www.wireshark.org/) but that's more for traffic on your entire network and not just the device.
