### ISSUE TITLE
Send data with POST request

### ISSUE THREAD

**Issue by shubham0987** [capacitor-community/http#208]
Hi Team,

I'm trying to do a post request with raw body data.

`const options: HttpOptions ={
      url,
      data: data,
      headers: {'Content-Type': 'text/plain'}
    };
    return from(Http.post(options));
  }`

On PHP API I'm not getting anything

`$request = \Slim\Slim::getInstance()->request();
    $data = json_decode($request->getBody());`

$data here is blank

Can someone help ?

**Comment by vamfixed** [comment]
i'm getting this too... when i tried on web i used json_decode(file_get_contents('php://input'), true);
but on real mobile device im getting null
