### ISSUE TITLE
Use node-fetch for web request

### ISSUE THREAD

**Issue by FernetB** [capacitor-community/http#209]
**Is your feature request related to a problem? Please describe.**
The current problem is that is imposible to use this plugin on node.

**Describe the solution you'd like**
I'm saw that this plugins uses fetch in web, adding the package node-fetch give us almost for free the possibility to use this on node

**Comment by thomasvidas** [comment]
Since Capacitor targets web, Android, and iOS; I'm not sure what node support would add. Plus the extra dependency isn't neccessary
