### ISSUE TITLE
How to send body in a Post request

### ISSUE THREAD

**Issue by loonix** [capacitor-community/http#25]
**Describe the bug**
I seem to be unable to send the body the http request

**To Reproduce**
```typescript
const req = await Http.request({
      method: 'GET',
      headers: headers,
      url: this.apiLink + '/tests',
      body: paths
    });
    return req.data;
```
**Smartphone (please complete the following information):**
 - Device: Iphone Emulator

Is it possible to send it as body? or is it through data?

**Comment by mlynch** [comment]
The field is `data` that you need
