### ISSUE TITLE
if http is not maintained, then what is the recommended plugin?

### ISSUE THREAD

**Issue by jayenashar** [capacitor-community/http#253]
**Is your feature request related to a problem? Please describe.**
When i visit this project in github, i see https://img.shields.io/maintenance/yes/2021?style=flat-square indicating this plugin is no longer maintained, but i'm not sure if that means i should or shouldn't use this plugin.  i am confused

**Describe the solution you'd like**
I'd like the README updated to tell me if i should use this plugin.  if i should not use this plugin, then i'd like some direction on what to use.

**Describe alternatives you've considered**
I searched google and [found a proposal for NHttp](https://github.com/ionic-team/capacitor/issues/5145) but don't know if it is available.

**Comment by thomasvidas** [comment]
I wouldn't say it's unmaintained. More like "maintenance mode." If there are critical security flaws I'll update the plugin. But for now there aren't and I unfortunately don't have time to work on new features. But the Ionic team plans on adding taking this plugin as a base for Capacitor 4 and making it a native plugin.

If this plugin _doesn't_ work for you, you could try `cordova-plugin-advanced-http`. But at the moment, this plugin works for many use cases and doesn't have any security issues.

**Comment by jayenashar** [comment]
fixed in 27dc4c858f1eb742622bc71c590f8aa351ef8221

thanks!
