### ISSUE TITLE
Sending request on background

### ISSUE THREAD

**Issue by matudelatower** [capacitor-community/http#258]
**Describe the bug**
Cant sent request in background with android, only sent when app is in foreground

**Expected behavior**
sending as a normal request

**Screenshots**
<img width="925" alt="image" src="https://user-images.githubusercontent.com/5694115/168584891-cfb48535-ec6d-45e7-a690-675c1ed2a7d7.png">

**Smartphone (please complete the following information):**
 - Device: Motorola Moto g(6)
 - OS: Android 9
 

**Additional context**
Use with Background geolocation plugin (https://github.com/capacitor-community/background-geolocation)

**Comment by Gladiatornoshield** [comment]
Hi [matudelatower](https://github.com/matudelatower) how are you able to get the post data on the API service. Do you mind sharing your http post examples. I have an API that works fine with Postman but when I post with this plugin I don't get the data I sent. Please help if your able to at least post the data to your server. Code snippet would be really helpful

**Comment by matudelatower** [comment]
i solved with background mode plugin, after 2 hours stop sending requests
