### ISSUE TITLE
Capacitor v4 support?

### ISSUE THREAD

**Issue by ptmkenny** [capacitor-community/http#276]
**Is your feature request related to a problem? Please describe.**

Capacitor v4 has been released and it would be great for this plugin to support v4.

There is [already a pull request for adding v4 support](https://github.com/capacitor-community/http/pull/275/commits).

I know this plugin is in maintenance mode as stated in the README on the project page, and that a [new official HTTP plugin will be added by the Ionic team](https://github.com/ionic-team/capacitor/issues/5145).

So, I would appreciate a statement by the maintainers as to whether this plugin will be updated to v4, or the recommendation is to just wait for official HTTP support to be added in Capacitor 4.x.

**Comment by dallastjames** [comment]
Hello!

We have no plans to update this plugin to support Capacitor v4, rather our efforts have been focused on building out the new official HTTP plugin. While I don't have any official timeline I can share, it is well underway!

**Comment by amuttsch** [comment]
We use this plugin using capacitor v4 successfully. We had to patch the min iOS version however. Otherwise it works great!

Heres the patchfile:

```
diff --git a/CapacitorCommunityHttp.podspec b/CapacitorCommunityHttp.podspec
index c6d63200fd261e4b6fac8ef4a920013ae89a3590..55a39a0a95a860c50ff3ea652038699311bedaf1 100644
--- a/CapacitorCommunityHttp.podspec
+++ b/CapacitorCommunityHttp.podspec
@@ -11,7 +11,7 @@ Pod::Spec.new do |s|
   s.author = package['author']
   s.source = { git: package['repository']['url'], tag: s.version.to_s }
   s.source_files = 'ios/Plugin/**/*.{swift,h,m,c,cc,mm,cpp}'
-  s.ios.deployment_target = '12.0'
+  s.ios.deployment_target = '13.0'
   s.dependency 'Capacitor'
   s.swift_version = '5.1'
 end
diff --git a/ios/Podfile b/ios/Podfile
index c0c11bda69005b23ad445551a1580d875e357ffd..95bd006cb57d21e930cf1d9d8adeb016c9131658 100644
--- a/ios/Podfile
+++ b/ios/Podfile
@@ -1,4 +1,4 @@
-platform :ios, '12.0'
+platform :ios, '13.0'
 
 def capacitor_pods
   # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
```

**Comment by thomasvidas** [comment]
I'm not sure if the official Http plugin will work with 4.0, or if will just be built into the Capacitor runtime itself. There were a few ideas bounced back and forth when I was still on the team. I could release another version based on #275 if the official plugin won't support 4.0, but rather 4.1+. Any insights on this @dallastjames?

**Comment by ptmkenny** [comment]
The [official HTTP plugin was added in Capacitor 4.3](https://capacitorjs.com/docs/apis/http), and there is a [now outdated release for this plugin](https://github.com/capacitor-community/http/releases/tag/v2.0.0-0), so I'm closing this issue.
