### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by abarrios003** [capacitor-community/http#28]
**Describe the bug**
Unable to test the plugin with development server running on localhost:8100

1. ionic serve --livereload 
2. Code: 
 const ret = await Http.request({
      method: 'GET',
      url: 'http://www.bilbao.eus/cs/Satellite?c=Page&cid=1272990237857&pageid=1272990237857&idioma=es&pagename=Bilbaonet/Page/BIO_ListadoEventosAppInfoBilbao&todos=si.json'
    });
    console.log(JSON.stringify(ret.data));

Working on devices but fails on browser 

 - Browser : Chrome / Firefox
-  Error traces:

from origin 'http://localhost:8100' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Thank you for your time and exceptional job!

**Comment by RTK** [comment]
When you are in a browser environment - Chrome/Firefox - you are restricted to the browser's conditions. Modern browsers all enforce CORS restrictions there is nothing this plugin can do. The only way to make this work is by having the requested server return the correct CORS headers (https://developer.mozilla.org/de/docs/Web/HTTP/CORS).

**Comment by mlynch** [comment]
As @RTK says, no way around this when running on the web. When running natively CORS will be bypassed, however

**Comment by kaleming** [comment]
@abarrios003, you can solve this doing:

`google-chrome --disable-site-isolation-trials --disable-web-security --user-data-dir="~/tmp"
`
