### ISSUE TITLE
Uploadfile Error: non-convertible Response

### ISSUE THREAD

**Issue by al-matari** [capacitor-community/http#35]
Hallo everyone,

the upload fails if the response is not a Json string. But the file can be found on the server. It seems to me that the plugin only works if the request and response are both Json-string.  E.g. the normal POST-requests ("Content-Type": "application/text; charset=UTF-8") will also fail if the attribute "Data" or the Response is not convertible string. 
Is that so or am I doing something wrong?

best regards,
Matari

**Comment by thomasvidas** [comment]
The latest version should have support for strings, base64 streams, and JSON, so I will close this issue. Feel free to re-open if you are still having problems 😄
