### ISSUE TITLE
Post does not append body to request

### ISSUE THREAD

**Issue by Apro123** [capacitor-community/http#48]
**Describe the bug**
When I do a post request, the http request does not send the json that is in the data field.

**To Reproduce**
Literally follow the tutorial

**Expected behavior**
A post request with the body.

**Desktop (please complete the following information):**
Browser Chrome/Brave

**Additional context**

**Comment by eskimo220** [comment]
the some problem.
When you send json data. You have to set `cotent-type: application/json` Header. 

sample:
```
// has json data
    if (vo.data) {
      // Content-Type
      vo.headers["Content-Type"] = "application/json";
    }
```

**Comment by Apro123** [comment]
Ahhh Silly me. Thanks @eskimo220

**Comment by mlynch** [comment]
Updated the docs to reflect this, thanks
