### ISSUE TITLE
iOS Security Cache Vulnerability

### ISSUE THREAD

**Issue by albafo** [capacitor-community/http#51]
When you make a request in iOS the information is stored and not encrypted in cache.db file

I suggest make an option in the interface to avoid caching the request.

**Comment by dwieeb** [comment]
If you set this header, does it still add unencrypted data to the Cache.db file? `Cache-Control: no-cache, no-store`

**Comment by thomasvidas** [comment]
Closing due to no response. The headers should suffice. If that is not the case, you can re-open this issue
