### ISSUE TITLE
client waits for server response before sending next request

### ISSUE THREAD

**Issue by cxFreeze** [capacitor-community/http#53]
**Describe the bug**
my server does not receive the next request before sending response to the client

**To Reproduce**

![K0g0iA4gxV](https://user-images.githubusercontent.com/19434393/94539338-62e36200-0245-11eb-9a86-21de501eb972.png)

**Expected behavior**

like angular http 

![P7ynLkWs4e](https://user-images.githubusercontent.com/19434393/94539407-78588c00-0245-11eb-9169-dd1f7db62fa2.png)

works also fine when using 'ionic serve'

**Screenshots**

what happens : 

![gPzeAAPr05](https://user-images.githubusercontent.com/19434393/94539500-9625f100-0245-11eb-8163-25a9ea493606.png)

**Smartphone (please complete the following information):**
 - Device: Redmi note 7 Android 10

**Additional context**

Can someone help ? i'm not sure if i'm doing something wrong.

thanks a lot.

**Comment by mghcs87** [comment]
I have the same problem, it only happens to me on android

**Comment by thomasvidas** [comment]
I believe PR #65 fixes this. If the upcoming 0.3.0 version does not fix this issue, feel free to re-open this issue
