### ISSUE TITLE
Support array of params for same key

### ISSUE THREAD

**Issue by filipegeric** [capacitor-community/http#59]
**Is your feature request related to a problem? Please describe.**
There is no way to send multiple query parameters for one key. For example:
`/users?status=ACTIVE&status=INACTIVE`

**Describe the solution you'd like**
It would be nice if the params object could accept both string and string array:
```javascript
{
  ...
  params: {
    status: ['ACTIVE', 'INACTIVE'],
    otherParam: 'example'
  }
  ...
}
```
which would result in the following URL: `/users?status=ACTIVE&status=INACTIVE&otherParam=example`.

**Describe alternatives you've considered**
An alternative to this would be to send multiple values separated by a comma: `/users?staus=ACTIVE,INACTIVE`. However, this would require the server to support this way of sending query params.

**Additional context**
This is a common way APIs handle filtering, therefore this would be a nice feature to have.

**Comment by thomasvidas** [comment]
Fixed in #122. Will be released with the next version of the HTTP plugin later today
