### ISSUE TITLE
No podspec found for `CapacitorCommunityHttp`

### ISSUE THREAD

**Issue by danielsogl** [capacitor-community/http#6]
**Describe the bug**
When running `npx cap sync` after installing the http plugin the following error is given out.

```bash
✖ Updating iOS native dependencies with "pod install" (may take several minutes): 
✖ update ios: 
[error] Error running update: Analyzing dependencies
[!] No podspec found for `CapacitorCommunityHttp` in `../../node_modules/@capacitor-community/http`
```

**Expected behavior**

The missing field should be deployed with the next plugin update

**Comment by priyankpat** [comment]
Yeah the reference to the filename is incorrect in package.json
