### ISSUE TITLE
Query params aren't sent with POST, PUT, or PATCH requests (android and iOS)

### ISSUE THREAD

**Issue by filipegeric** [capacitor-community/http#61]
**Describe the bug**
Query params aren't sent with POST, PUT, or PATCH requests.

**To Reproduce**
```javascript
const doPost = () => {
  const { Http } = Plugins;

  const ret = await Http.request({
    method: 'POST',
    url: 'https://example.com/my/api',
    headers: {
      'X-Fake-Header': 'Max was here',
      'Content-Type': 'application/json'
    },
    params: {
       size: 'XL'
    },
    data: {
      foo: 'bar',
      cool: true
    }
  });
}
```

**Expected behavior**
It would make sense that the request is sent with the provided query params:
`POST https://example.com/my/api?size=XL`

**Comment by muuvmuuv** [comment]
See: https://github.com/capacitor-community/http/pull/46

**Comment by filipegeric** [comment]
This is related only to the web platform @muuvmuuv

**Comment by muuvmuuv** [comment]
Yes, true. I didn't add that. Can you edit your title to mention "native"?

**Comment by thomasvidas** [comment]
Closing since `1.0.0-alpha.0` is on npm under `@capacitor-community/http@next` and should fix this issue
