### ISSUE TITLE
URL paths are decoded prior to request on Android

### ISSUE THREAD

**Issue by SpenceDiNicolantonio** [capacitor-community/http#62]
**Describe the bug**
When making a request to a URL that includes encoded characters (e.g. `%2F`), those character sequences are decoded prior to making the the request. This breaks requests that expect such escape sequences (e.g. Firebase storage refs).

**Example:**
`https://firebasestorage.googleapis.com/v0/b/xxxxxx/o/path%2Fto%2Ffile.json` becomes `https://firebasestorage.googleapis.com/v0/b/xxxxxx/o/path/to/file.json`

This is caused by the following line in the `setParams()` method, due to the use of `URI.getPath()` which returns a decoded path:
`URI newUri = new URI(uri.getScheme(), uri.getAuthority(), uri.getPath(), newQuery, uri.getFragment());`

**To Reproduce**
1. Invoke the Http plugin on an Android device or simulator, using a URL containing an encoded character sequence

**Expected behavior**
A request is made to the provided URL, as it was provided

**Smartphone (please complete the following information):**
 - Device: Pixel 2 Simulator
 - OS: Android
 - Browser: Stock web view
 - Version: API 30

**Comment by arasrezaei** [comment]
does any one know how to fix this?

**Comment by SpenceDiNicolantonio** [comment]
> does any one know how to fix this?

@arasrezaei I was unable to find a solution - we ended up restructuring our Firebase storage to avoid it 😒

**Comment by mcasami-frit** [comment]
Good morning, I had problems with this topic. Finally use JS's own encodeURI (). It seems to work.

**Comment by dodomui** [comment]
@mcasami-frit encodeURI() doesn't work for me.

@SpenceDiNicolantonio Do you store all the images on root without any subfolder? But it will mess up the structure.

@arasrezaei Me too, having this issue on android.

Any solution for android?

**Comment by jabi11** [comment]
same here
