### ISSUE TITLE
POST Data is not passing.

### ISSUE THREAD

**Issue by tonraj** [capacitor-community/http#67]
**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 88.0.4324.11 (Official Build) dev (64-bit)

Trying to use in Ionic Vue.

Http.request({
        method: 'POST',
        url: ApiHost + '/api/v1/seller/login',
        data: {phone : this.phone, password: this.password},
        headers: {
          'X-Fake-Header': 'Max was here'
        },
        params: {
          size: 'XL'
        }
      }).then((res)=>{
            if(res.status == 200){
              Storage.set({ key: 'token', value: res.data.token }).then((res)=>{
                  this.route.push('/register/step/2');
              });
            }else{
              this.logging = false;
            }
      });

**Comment by luisgonptl** [comment]
Having the same issue.

**Comment by luisgonptl** [comment]
Check that you are adding the "add(Http.class);" in your android MainActivity.

**Comment by tonraj** [comment]
> Check that you are adding the "add(Http.class);" in your android MainActivity.

I did.

**Comment by luisgonptl** [comment]
Try remove params, and move the size property to data.
POST -> data goes in data
GET -> data goes in params

**Comment by tonraj** [comment]
> POST

Yeah I did but nothing goes inside DATA.

**Comment by KimGnab** [comment]
How did you solve the cors error in AXIOS?

**Comment by KimGnab** [comment]
> > POST
> 
> Yeah I did but nothing goes inside DATA.
> 
> I moved to AXIOS closing the issue.

How did you solve the cors error in AXIOS?

**Comment by butaminas** [comment]
This seems to be an old issue but I have the exact same problem.
I only set `data` (my post request parameters), `headers` and `url` in the config that I pass to `Http.post(config)`.

For some reason, the post parameters are never passed.
