### ISSUE TITLE
API request with non ascii characters brokes the server response

### ISSUE THREAD

**Issue by SalahAdDin** [capacitor-community/http#71]
**Describe the bug**
We are having a big problem with this encoding here:
<img width="885" alt="Screen Shot 2021-01-07 at 13 06 25" src="https://user-images.githubusercontent.com/5034215/104024198-cc272980-51d3-11eb-96d7-a6157210d695.png">

This is a request made from our application to the backend: getting a bug.
![Screenshot from 2021-01-07 17-29-09](https://user-images.githubusercontent.com/5034215/104024277-f24cc980-51d3-11eb-8e1c-abca98a2238a.png)

Every time we sent text with Turkish character from the application we get this bug; looking on how fixing this we meet this pull request which seems to solve the bug, but this pull request is not yet in the last plugin's version.

**To Reproduce**
1. Create an object with some non ascii character to be the request body.
2. Send the request to the backend through the api.
3. Get the response from the server on the console log.

**Expected behavior**
A true response from the backend.

**Screenshots**
<img width="885" alt="Screen Shot 2021-01-07 at 13 06 25" src="https://user-images.githubusercontent.com/5034215/104024198-cc272980-51d3-11eb-96d7-a6157210d695.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device:  Lenovo Tab M10 (FHD)
 - OS: Android 9
 - Version 0.2.1

**Additional context**
There is a possible [solution](https://github.com/capacitor-community/http/pull/41#issuecomment-756773450) already in this plugin's base code, but it is not in the last version.

**Comment by thomasvidas** [comment]
This is already fixed on `master` in #41 so I'm closing this. A new npm version will be out later this week if everything goes well!
