### ISSUE TITLE
204 crash on chrome (json)

### ISSUE THREAD

**Issue by matEhickey** [capacitor-community/http#76]
**Describe the bug**  
http.request crash with the error 'Uncaught SyntaxError: Unexpected end of JSON input', when the server return a 204.  
When investigating, it really look like the method try to "JSON.parse('')", and throw the error, instead of a type 204.  
It's working fine on mobile devices (at least on android), and on firefox.  

**To Reproduce**
```js
Http.request({
    method,
    url,
 }).then(response => {
    if(response.status === 204) console.warn("204")
  }).catch(e => {
     console.warn(e)
});
```

In firefox, mobile, it show the 204 message
On chrome, it show the 'Uncaught SyntaxError: Unexpected end of JSON input'

**Expected behavior**
On chrome, it should have the same behavior than on firefox-> to succeed, with the status value set to 204

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: chrome
 - Version 87.0.4280.141

**Comment by matEhickey** [comment]
May impact others errors, it seem to also appear when there is no internet connection too

**Comment by SalahAdDin** [comment]
Could it be related to `utf-8` encoding?

**Comment by matEhickey** [comment]
Maybe, can I try something ?

**Comment by thomasvidas** [comment]
Can you try upgrading to the new 0.3.0 release on npm? I think that might fix your issue

**Comment by SalahAdDin** [comment]
@thomasvidas i will test it tomorrow at first.

**Comment by matEhickey** [comment]
Hello. I just tested it now and it look that the problem is still here. I tested only the chrome reproduction case tho ("SyntaxError: Unexpected end of JSON input")

**Comment by thomasvidas** [comment]
Is this still present on the `1.0.0-alpha.0` version on npm? Very odd this is happening on Chrome only

**Comment by thomasvidas** [comment]
Closing due to no response

**Comment by fr3fou** [comment]
I'm also experiencing the same issue, using 1.0.0

**Comment by fr3fou** [comment]
Seem to also be experiencing the same issue on Android too
