### ISSUE TITLE
downloadFile and uploadFile ignore headers object

### ISSUE THREAD

**Issue by ynunez** [capacitor-community/http#79]
**Describe the bug**

When downloading or uploading a file from a protected resource and sending an authorization header (or any other headers) the native iOS code doesn't use the headers to build the request.

**Environments**

- [ ] Android
- [x] iOS

**To Reproduce**

```
const options: any = {
      url: https://your-host/proteced-download,
      name: 'file',
      filePath: filePath,
      headers: {
        Authorization: `Bearer ${accessToken}`
      }
 };

Http.uploadFile(options)
```

**Expected behavior**

Both `HttpDownloadFileOptions` and `HttpDownloadFileOptions` extend `HttpDownloadFileOptions` which has the `headers` object as an optional parameter. The download/upload functions should accept the headers object like it does on Android.

**Comment by thomasvidas** [comment]
Fixed already in `capacitor-v3`
