### ISSUE TITLE
request on android 9 not working

### ISSUE THREAD

**Issue by camaragit** [capacitor-community/http#92]
I get this response {message: "Error"} when i try to make request in android .But it works fine on the browser. here is my envronnement :

Ionic:

   Ionic CLI                     : 6.1.0 (C:\Users\Dame\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.1101.1
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 11.1.1
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.6
   @capacitor/core : 2.4.6

Utility:

   cordova-res : 0.8.1
   native-run  : 0.2.9

System:

   NodeJS : v12.13.1 (G:\Program Files\nodejs\node.exe)
   npm    : 6.14.5
   OS     : Windows 10

**Comment by thomasvidas** [comment]
Hello 👋 
- can you provide a reproducible example?
- what version of the plugin are you on?

**Comment by filpet95** [comment]
Try option #2 here: https://stackoverflow.com/a/50834600

**Comment by thomasvidas** [comment]
Closing due to lack of reply

**Comment by faroukh-dev** [comment]
are there a solving solution for that?

**Comment by itshazlan** [comment]
> Try option 2 here: https://stackoverflow.com/a/50834600

i have tried these solution, but there is no workaround of these answer :((
