### ISSUE TITLE
Http.downloadFIle call resolve twice. 

### ISSUE THREAD

**Issue by leo6104** [capacitor-community/http#93]
**Describe the bug**
https://github.com/capacitor-community/http/blob/master/ios/Plugin/Plugin.swift#L85

it has `call.resolve` two statement. 

**Expected behavior**
 It should call one time. 

**Screenshots**
![image](https://user-images.githubusercontent.com/7777929/106932912-a69e2900-675b-11eb-9bbd-c454937c0057.png)

**Desktop (please complete the following information):**
 - OS: iOS

**Additional context**

**Comment by thomasvidas** [comment]
Closing this is fixed in `1.0.0-alpha.0` is on npm under `@capacitor-community/http@next`.
