### ISSUE TITLE
Add Timeout Support to iOS

### ISSUE THREAD

**Issue by ryaa** [capacitor-community/http#95]
**Is your feature request related to a problem? Please describe.**
It seems that the timeout (both connectTimeout and readTimeout) is supported on Android however similar feature is not available for iOS platform. 

**Describe the solution you'd like**
Support timeout for http requests for both, iOS and Android.

**Describe alternatives you've considered**
The cordova-plugin-advanced-http cordova plugin supports this feature https://github.com/silkimen/cordova-plugin-advanced-http#setrequesttimeout (even though there are some caveats - see https://github.com/silkimen/cordova-plugin-advanced-http/pull/316)

**Additional context**
N/A

**Comment by thomasvidas** [comment]
Yes, it should work the same across both platforms. The timeout should be added to iOS

**Comment by thomasvidas** [comment]
Closing since `1.0.0-alpha.0` is on npm under `@capacitor-community/http@next`.

Since iOS and Android behave differently (iOS only having a single timeout), `connectTimeout` is prioritized over `readTimeout`. If neither are set, the default timeout of 60 seconds is set instead on iOS

**Comment by andreixk** [comment]
The plugin works, however, when running `npx cap sync`, I'm getting the error: 
_CocoaPods could not find compatible versions for pod "CapacitorCommunityHttp"_
