### ISSUE TITLE
Inconsistent results when calling API from different platforms

### ISSUE THREAD

**Issue by lukemovement** [capacitor-community/http#96]
I'm sure if this is an issue with the platforms, my backend (old framework), or this package.

When making an HTTP request with a body of data different configuration needs to be used for iOS and Android.

When using "application/x-www-form-urlencoded" with iOS results in the requests data being decoded automatically.
When using "application/json" with Android the requests data is empty.

The issues below resolve themselves when using "application/json" on iOS and "application/x-www-form-urlencoded" for Android.

**To Reproduce**
IOS:
`{
    url: string,
    method: "POST",
    data: { "email": "email+address@email.com" },
    headers: { "Content-Type": "application/x-www-form-urlencoded" }
}`

The body received by the server `{ "email": "email address@email.com" }`

Android:
Request `{
    url: string,
    method: "POST",
    data: { "email": "email+address@email.com" },
    headers: { "Content-Type": "application/json" }
}`

The body received by the server `{}`

**Expected behaviour**
Results should be consistent across platforms, where $_POST['email'] would return "email+address@email.com"

**Smartphone: IOS**
 - Device: Emulator
 - OS: iOS12, iOS12.4, iOS14.4
(Apple tester also experienced this issue when testing the app before approving it for the App Store, the test on physical devices)

**Smartphone: Android**
 - Device: Emulator, Redmi Note 9, Samsung S6
 - OS: Android 6, 10

**Comment by thomasvidas** [comment]
Hello 👋  Thanks for the issue. A couple questions.

Can you provide a sample project/server where the exact error is happening? 
What version of Capacitor are you using?
What version of the HTTP plugin are you using?

**Comment by thomasvidas** [comment]
Closing due to no response. Please re-open if this is still an issue 😄
